name: test-push

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/checkout@v3
        with:
          repository:  IBM/network-config-analyzer
          path: network-config-analyzer
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
          architecture: x64

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install -r network-config-analyzer/requirements.txt
      - name: Lint with flake8
        run: flake8 src --count --max-complexity=10 --max-line-length=127 --statistics
      - name: Run all tests
        env:
          GHE_TOKEN: ${{ github.token }}
        run: |
          cd tests
          python run_all_tests.py --nca_path ${{ github.workspace }}/network-config-analyzer/network-config-analyzer
